name: Deploy MkDocs Site to WebDAV

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger this on

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material mkdocs-mermaid2-plugin  # or other plugins/themes you need

      - name: Build MkDocs site
        run: mkdocs build

      - name: Delete old folder on WebDAV server
        env:
          WEBDAV_USER: ${{ secrets.WEBDAV_USER }}
          WEBDAV_PASS: ${{ secrets.WEBDAV_PASS }}
          WEBDAV_URL: ${{ secrets.WEBDAV_URL }}
        run: |
          curl -X DELETE -u "$WEBDAV_USER:$WEBDAV_PASS" "$WEBDAV_URL/public/" || echo "Folder does not exist, skipping deletion"

      - name: Upload MkDocs site to WebDAV
        env:
          WEBDAV_USER: ${{ secrets.WEBDAV_USER }}
          WEBDAV_PASS: ${{ secrets.WEBDAV_PASS }}
          WEBDAV_URL: ${{ secrets.WEBDAV_URL }}
        run: |
          # Upload each file to the WebDAV server
          for file in $(find site -type f); do
            relative_path="${file#site/}"
            curl -T "$file" -u "$WEBDAV_USER:$WEBDAV_PASS" "$WEBDAV_URL/public/$relative_path"
          done
