name: Building and Deploying MKDOCS to webdav

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-mermaid2-plugin

      - name: Build MkDocs site
        run: mkdocs build -d site
        working-directory: DOCS

      - name: Install curl for webdav
        run: sudo apt-get install -y curl

      - name: Clean WebDAV directory
        env:
          WEBDAV_USERNAME: ${{ secrets.WEBDAV_USERNAME }}
          WEBDAV_PASSWORD: ${{ secrets.WEBDAV_PASSWORD }}
        run: |
          # List files and delete each
          curl -u "$WEBDAV_USERNAME:$WEBDAV_PASSWORD" -X PROPFIND "${{ secrets.WEBDAV_URL }}/" -H "Depth: 1" | grep -oP '(?<=<d:href>).*?(?=</d:href>)' | while read -r file; do
            if [ "$file" != "/" ]; then
              # Delete the file or directory
              curl -u "$WEBDAV_USERNAME:$WEBDAV_PASSWORD" -X DELETE "${{ secrets.WEBDAV_URL }}${file}"
            fi
          done

      - name: Deploy to WebDAV
        env:
          WEBDAV_USERNAME: ${{ secrets.WEBDAV_USERNAME }}
          WEBDAV_PASSWORD: ${{ secrets.WEBDAV_PASSWORD }}
        run: |
          find site -type f | while read file; do
            remote_file="${{ secrets.WEBDAV_URL }}/$(echo $file | sed 's|site/||')"
            curl -u "$WEBDAV_USERNAME:$WEBDAV_PASSWORD" -T "$file" "$remote_file"
          done
